# Generated by Django 3.1.2 on 2020-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=500)),
                ('address_line_2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('province', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
